# (<class>.)membername(<argtype>(, ...<argtype>)) = (<class>.)membername(<argtype>(, ...<argtype>))

# resolve ambiguities
Highs.passModel(HighsModel) = Highs.passModel(HighsModel)
Highs.setCallback((callbackType: number, msg: string, dataOut: HighsCallbackDataOut, dataIn: HighsCallbackDataIn, user_callback_data: any) => void, any) = highs_setCallback(Highs &, Callback, CallbackData)
Highs.startCallback(HighsCallbackType) = Highs.startCallback(HighsCallbackType)
Highs.stopCallback(HighsCallbackType) = Highs.stopCallback(HighsCallbackType)
Highs.changeColsCost(number, number[], number[]) = Highs.changeColsCost(HighsInt, HighsInt *, double *)
Highs.changeColsBounds(number, number[], number[], number[]) = Highs.changeColsBounds(HighsInt, HighsInt *, double *, double *)
Highs.changeColsIntegrality(number, number[], HighsVarType[]) = Highs.changeColsIntegrality(HighsInt, HighsInt *, HighsVarType *)
Highs.deleteCols(number, number[]) = Highs.deleteCols(HighsInt, HighsInt *)
Highs.deleteVars(number, number[]) = Highs.deleteVars(HighsInt, HighsInt *)
Highs.deleteRows(number, number[]) = Highs.deleteRows(HighsInt, HighsInt *)
Highs.setOptionValue(EmbindString, string | number | boolean) = highs_setOptionValue(Highs &, string, OptionType)

# map vector classes
IntVector = std::vector
DoubleVector = std::vector
StringVector = std::vector
HighsVarTypeVector = std::vector
HighsObjectiveSolutionVector = std::vector
HighsIisInfoVector = std::vector
OptionRecordVector  = std::vector
InfoRecordVector = std::vector
HighsBasisStatusVector = std::vector

# map renamed / redefined functions
Highs.passLp(HighsLp) = highs_passLp(Highs &, HighsLp &)
Highs.getRanging() = highs_getRanging(Highs &)
Highs.getObjectiveSense() = highs_getObjectiveSense(Highs &)
Highs.getObjectiveOffset() = highs_getObjectiveOffset(Highs &)
Highs.setBasis(HighsBasis) = Highs.setBasis(Highs&, HighsBasis&)
Highs.getCol(number) = highs_getCol(Highs&, HighsInt)
Highs.getColEntries(number) = highs_getColEntries(Highs&, HighsInt)
Highs.getRow(number) = highs_getRow(Highs&, HighsInt)
Highs.getRowEntries(number) = highs_getRowEntries(Highs&, HighsInt)
Highs.getCols(number, number[]) = highs_getCols(Highs&, HighsInt, IntArray)
Highs.getColsEntries(number, number[]) = highs_getColsEntries(Highs&, HighsInt, IntArray)
Highs.getRows(number, number[]) = highs_getRows(Highs&, HighsInt, IntArray)
Highs.getRowsEntries(number, number[]) = highs_getRowsEntries(Highs&, HighsInt, IntArray)
Highs.getColName(number) = highs_getColName(Highs&, HighsInt)
Highs.getRowName(number) = highs_getRowName(Highs&, HighsInt)
Highs.startCallbackInt(number) = Highs.startCallback(int)
Highs.stopCallbackInt(number) = Highs.stopCallback(int)
Highs.passLp(number, number, number, number, number, number, number[], number[], number[], number[], number[], number[], number[], number[], number[]) = highs_passLpPointers(Highs&, HighsInt, HighsInt, HighsInt, HighsInt, double, DoubleArray, DoubleArray, DoubleArray, DoubleArray, DoubleArray, IntArray, IntArray, DoubleArray, IntArray)
Highs.getOptionValue(EmbindString) = highs_getOptionValue(Highs&, std::string&)
Highs.getOptionType(Embindstring) = highs_getOptionType(Highs&, std::string&)
Highs.getInfoValue(EmbindString) = highs_getInfoValue(Highs&, std::string&)
Highs.getInfoType(Embindstring) = highs_getInfoType(Highs&, std::string&)
Highs.writeOptions(EmbindString) = highs_writeOptions(Highs&, std::string&)
Highs.getColByName(EmbindString) = highs_getColByName(Highs&, std::string)
Highs.getRowByName(EmbindString) = highs_getRowByName(Highs&, std::string)