on: [push, pull_request]

name: Continuous Integration

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: mymindstorm/setup-emsdk@v14
        with: { version: "3.1.71" }
      - run: >
        curl -L https://github.com/doxygen/doxygen/releases/download/Release_1_12_0/doxygen-1.12.0.linux.bin.tar.gz | tar -xz &&
        cd doxygen-1.12.0 && make install && cd .. && rm -r doxygen-1.12.0
      - run: npm ci
      - name: build
        run: npm run build
      - name: test
        run: npm test
