on: [push, pull_request]

name: Create a release

jobs:
  build:
    name: Create a release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mymindstorm/setup-emsdk@f9068d69f3908ddd991f32b8c8818d5781fe0c78
        with: {version: '2.0.15'}
      - name: build
        run: cd build && ./build.sh
      - name: test
        run: npm test
