on: [push, pull_request]

name: Continuous Integration

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: mymindstorm/setup-emsdk@ca0cef33e53bf9149891246a1b13ef3dbd498ca5
        with: {version: '2.0.31'}
      - run: npm ci
      - name: build
        run: npm run build
      - name: test
        run: npm test
